### ISSUE TITLE
Create and Bulk remove is not working

### ISSUE THREAD

**Issue by srako** [bee-queue/arena#221] opened 2020-05-16 03:36 UTC
I am also still experiencing this issue, 
``` json
{ 
    "bee-queue": "^1.2.3",
    "bull-arena": "^2.8.1",
}
```

``` javascript
const Arena = require('bull-arena');
module.exports = options => {
  return async function arena(ctx, next) {
    if (ctx.request.url !== '/arena' && !ctx.request.url.startsWith('/arena/')) {
      return await next();
    }

    const arena = Arena({
      queues: [
        {
          name: 'queue',
          hostId: 'Async Queue',
          type: 'bee',
          prefix: 'monitor',
          redis: ctx.app.redis,
        },
        {
          name: 'delay_queue',
          hostId: 'Delay Queue',
          type: 'bee',
          prefix: 'monitor',
          redis: ctx.app.redis,
        },
      ],
    }, {
      basePath: '/arena', // the url prefix you want
      disableListen: true, // do not start express server, let koa handle instead
      useCdn: true,
    });

    ctx.status = 200;
    ctx.respond = false;
    return await arena(ctx.req, ctx.res);
  };
};
```
network pending
I am running this as as a node_module in an egg middleware.

_Originally posted by @srako in https://github.com/bee-queue/arena/issues/101#issuecomment-629579946_

**Comment by skeggse** [comment] 2020-10-28 06:30
Does this work in express instead of koa?

**Comment by shiningstarts** [comment] 2020-11-23 06:13
> Does this work in express instead of koa?

It happens in my project, but it works well when I use express.

**Comment by skeggse** [comment] 2020-11-25 18:39
We don't officially support koa, and don't have the bandwidth to pursue it. If you find a valid issue when using arena with express, feel free to re-open! Otherwise, I'll consider this a duplicate of #161.

**Closed by skeggse** 2020-11-25 18:39 UTC
Labels: bug
