### ISSUE TITLE
Bulk remove is not working when running as a node module.

### ISSUE THREAD

**Issue by moltar** [bee-queue/arena#101] opened 2018-06-08 14:43 UTC
All other routes/actions seem to work, even the single job delete. But the bulk remove hangs and never completes. Tried debugging it, and it seems like it's not even hitting the route handler.

**Comment by rosshadden** [comment] 2018-07-02 02:16
I have the same issue. I found that there are three cases in which I can get that call to hit the endpoint:

1. I don't send the `Content-Type` header
2. I don't send the data payload itself
3. I comment out [the JSON body parser](https://github.com/bee-queue/arena/blob/55de833df4adca0b6558c469a56f4a21e6fd2df0/src/server/app.js#L33)

Thus I think it's a problem with the json body parser, but I couldn't figure out how to fix it.

**Comment by moltar** [comment] 2018-07-02 14:28
So is it a problem maybe that the JSON was already pre-parsed by the server that integrates the arena?

**Comment by scottbasgaard** [comment] 2018-08-08 20:38
Have this issue as well.

**Comment by tidusvn05** [comment] 2018-08-09 04:30
I have the same issue.
{
  "error": "queue error",
  "details": "Error: Could not remove job

**Comment by scottbasgaard** [comment] 2018-08-09 11:48
>All other routes/actions seem to work, even the single job delete. But the bulk remove hangs and never completes. Tried debugging it, and it seems like it's not even hitting the route handler.

Can confirm, single job delete works, it's the bulk one.

**Comment by milesalex** [comment] 2018-08-14 19:52
Same issue here

**Comment by ttacon** [comment] 2018-08-18 03:04
Is there a test config or setup that someone can provide that reproduces the issue?

**Comment by scottbasgaard** [comment] 2018-08-30 08:48
I'm not sure what changed on my application end but this now works again... 🙏

**Comment by ttacon** [comment] 2018-08-30 14:10
Can someone else that is still experiencing this provide a config that reproduces the error? Otherwise, I'll close this next week.

**Comment by ttacon** [comment] 2018-09-07 13:32
Closing this due to lack of activity/a reproducible config. Happy to reopen this if someone can provide a config to repro this issue!

**Closed by ttacon** 2018-09-07 13:32 UTC

**Comment by milesalex** [comment] 2019-01-23 22:17
Hey, still getting this issue, How can I help with reproing it:

https://d.pr/i/v0Awi3

**Comment by dhritzkiv** [comment] 2019-03-04 21:40
I am also still experiencing this issue, however, only on Active Jobs. Is it because they have a lock that they are non-removable?

**Comment by srako** [comment] 2020-05-16 03:13
I am also still experiencing this issue, 
```
{ 
    "bee-queue": "^1.2.3",
    "bull-arena": "^2.8.1",
}
```

```
const Arena = require('bull-arena');
module.exports = options => {
  return async function arena(ctx, next) {
    if (ctx.request.url !== '/arena' && !ctx.request.url.startsWith('/arena/')) {
      return await next();
    }

    const arena = Arena({
      queues: [
        {
          name: 'queue',
          hostId: 'Async Queue',
          type: 'bee',
          prefix: 'monitor',
          redis: ctx.app.redis,
        },
        {
          name: 'delay_queue',
          hostId: 'Delay Queue',
          type: 'bee',
          prefix: 'monitor',
          redis: ctx.app.redis,
        },
      ],
    }, {
      basePath: '/arena', // the url prefix you want
      disableListen: true, // do not start express server, let koa handle instead
      useCdn: true,
    });

    ctx.status = 200;
    ctx.respond = false;
    return await arena(ctx.req, ctx.res);
  };
};
```
network pending
I am running this as as a node_module in an egg middleware.
